version: '3.4'
services:
  jbd.user.web:
    image: jbd.user.web/user-info-web
    container_name: user-info-web
    build:
      context: .
      dockerfile: user-info-web/Dockerfile
    ports:
      - "8180:8080"
    environment:
      - SPRING_MAIN_BANNER-MODE=CONSOLE
      - SPRING_CONFIG_LOCATION=file:/usr/src/app/config/application.properties
    volumes:
      - ./tools/env:/usr/src/app/config

  dbpostgres:
    restart: always
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=user_info
    volumes:
      - postgres1:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis1:/data

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - mongo1:/data/db

  jaeger:
    image: jaegertracing/all-in-one:1.7
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: "9411"

volumes:
  postgres1:
    driver: local
  redis1:
    driver: local
  mongo1:
    driver: local
