version: '3.4'
services:
  dbpostgres:
    restart: always
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=DEMO
    volumes:
      - postgres1:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis1:/data

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - mongo1:/data/db

volumes:
  postgres1:
    driver: local
  redis1:
    driver: local
  mongo1:
    driver: local
