
INSERT INTO JBD_USER(ID, LOGIN, PASSWORD, ENABLED) VALUES (1, 'user', '$2a$10$E1dTcmjJaWcNOAQQ63bDheOyto3jLzzSD1fcfs8AwTK8qc2d0cI6W', true);
INSERT INTO JBD_USER_ROLE(LOGIN, ROLE) VALUES ('user', 'USER');
INSERT INTO JBD_USER_INFO(ID, USER_ID, NAME, LAST_NAME, EMAIL, PHONE_NUMBER) VALUES (1, 1, 'User', 'Santos', 'user@gmail.com', '123456789');
INSERT INTO JBD_USER_ADDRESS(ID, USER_ID, STREET, NUMBER, CITY, STATE, COUNTRY) VALUES(1, 1, 'Av. Paulista', '1200', 'Sao Paulo', 'SP', 'Brasil');
INSERT INTO JBD_USER_ADDRESS(ID, USER_ID, STREET, NUMBER, CITY, STATE, COUNTRY) VALUES(2, 1, 'Rua Augusta', '350', 'Sao Paulo', 'SP', 'Brasil');

INSERT INTO JBD_USER(ID, LOGIN, PASSWORD, ENABLED) VALUES (10, 'admin', '$2a$10$E1dTcmjJaWcNOAQQ63bDheOyto3jLzzSD1fcfs8AwTK8qc2d0cI6W', true);
INSERT INTO JBD_USER_ROLE(LOGIN, ROLE) VALUES ('admin', 'USER');
INSERT INTO JBD_USER_ROLE(LOGIN, ROLE) VALUES ('admin', 'ADMIN');
INSERT INTO JBD_USER_INFO(ID, USER_ID, NAME, LAST_NAME, EMAIL, PHONE_NUMBER) VALUES (10, 10, 'Admin', 'da Silva', 'admin@gmail.com', '987654321');
INSERT INTO JBD_USER_ADDRESS(ID, USER_ID, STREET, NUMBER, CITY, STATE, COUNTRY) VALUES(10, 10, 'Av. dos Bandeirantes', '3330', 'Sao Paulo', 'SP', 'Brasil');

INSERT INTO JBD_USER(ID, LOGIN, PASSWORD, ENABLED) VALUES (20, 'actuator', '$2a$10$E1dTcmjJaWcNOAQQ63bDheOyto3jLzzSD1fcfs8AwTK8qc2d0cI6W', true);
INSERT INTO JBD_USER_ROLE(LOGIN, ROLE) VALUES ('actuator', 'USER');
INSERT INTO JBD_USER_ROLE(LOGIN, ROLE) VALUES ('actuator', 'ACTUATOR');
INSERT INTO JBD_USER_INFO(ID, USER_ID, NAME, LAST_NAME, EMAIL, PHONE_NUMBER) VALUES (20, 20, 'Actuator', 'Souza', 'actuator@gmail.com', '456123789');
INSERT INTO JBD_USER_ADDRESS(ID, USER_ID, STREET, NUMBER, CITY, STATE, COUNTRY) VALUES(20, 20, 'Av. Faria Lima', '1500', 'Sao Paulo', 'SP', 'Brasil');
