
INSERT INTO JBD_USER(LOGIN, PASSWORD, ENABLED) VALUES ('user', '$2a$10$E1dTcmjJaWcNOAQQ63bDheOyto3jLzzSD1fcfs8AwTK8qc2d0cI6W', true);
INSERT INTO JBD_USER_ROLE(LOGIN, ROLE) VALUES ('user', 'USER');

INSERT INTO JBD_USER(LOGIN, PASSWORD, ENABLED) VALUES ('admin', '$2a$10$E1dTcmjJaWcNOAQQ63bDheOyto3jLzzSD1fcfs8AwTK8qc2d0cI6W', true);
INSERT INTO JBD_USER_ROLE(LOGIN, ROLE) VALUES ('admin', 'USER');
INSERT INTO JBD_USER_ROLE(LOGIN, ROLE) VALUES ('admin', 'ADMIN');

INSERT INTO JBD_USER(LOGIN, PASSWORD, ENABLED) VALUES ('actuator', '$2a$10$E1dTcmjJaWcNOAQQ63bDheOyto3jLzzSD1fcfs8AwTK8qc2d0cI6W', true);
INSERT INTO JBD_USER_ROLE(LOGIN, ROLE) VALUES ('actuator', 'USER');
INSERT INTO JBD_USER_ROLE(LOGIN, ROLE) VALUES ('actuator', 'ACTUATOR');
